DROP TABLE IF EXISTS job;
DROP TABLE IF EXISTS location;
DROP TABLE IF EXISTS salary;
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE job(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  job_name TEXT NOT NULL,
  job_location TEXT NOT NULL,
  job_salary NUMBER NOT NULL
);

